#!/usr/bin/env php
<?php

date_default_timezone_set('UTC');

set_time_limit(0);

require_once __DIR__ . '/../vendor/autoload.php';

use Inachis\Component\JiraIntegration\Console\Application;

$app = new Application();
$app->run();
